

/*function form(){
    return(
      
CREAR UN NUEVO COMPONENTE LLAMADO FORM
CREAR FUNCION HANDLECHANGEFORM
EN APP HAY QUE CAMBIAR LA FUNCION PARA QUE RECIBA EL EVENTO HANDLECHANGEFORM QUE TENEMOS QUE CREAR EN FORM, Y QUE SOLO RECIBA LA FUNCION EN APP EL ID Y EL VALUE PARA QUE HAGA LOS CONDICIONALES.
CAMBIAR NOMBRE DE LA FUNCION APP YA QUE DEJA DE HACER EL EVENTO .
    );
}
export default form;*/